/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./OmniflixMinterFactory.types";
import * as _1 from "./OmniflixMinterFactory.client";
import * as _2 from "./OmniflixMinterFactory.message-composer";
import * as _3 from "./OmniflixOpenEditionMinterFactory.types";
import * as _4 from "./OmniflixOpenEditionMinterFactory.client";
import * as _5 from "./OmniflixOpenEditionMinterFactory.message-composer";
import * as _6 from "./OmniflixRoundWhitelistFactory.types";
import * as _7 from "./OmniflixRoundWhitelistFactory.client";
import * as _8 from "./OmniflixRoundWhitelistFactory.message-composer";
import * as _9 from "./OmniflixRoundWhitelist.types";
import * as _10 from "./OmniflixRoundWhitelist.client";
import * as _11 from "./OmniflixRoundWhitelist.message-composer";
import * as _12 from "./OmniflixMinter.types";
import * as _13 from "./OmniflixMinter.client";
import * as _14 from "./OmniflixMinter.message-composer";
import * as _15 from "./OmniflixOpenEditionMinter.types";
import * as _16 from "./OmniflixOpenEditionMinter.client";
import * as _17 from "./OmniflixOpenEditionMinter.message-composer";
import * as _18 from "./OmniflixMultiMintOpenEditionMinter.types";
import * as _19 from "./OmniflixMultiMintOpenEditionMinter.client";
import * as _20 from "./OmniflixMultiMintOpenEditionMinter.message-composer";
export namespace contracts {
  export const OmniflixMinterFactory = { ..._0,
    ..._1,
    ..._2
  };
  export const OmniflixOpenEditionMinterFactory = { ..._3,
    ..._4,
    ..._5
  };
  export const OmniflixRoundWhitelistFactory = { ..._6,
    ..._7,
    ..._8
  };
  export const OmniflixRoundWhitelist = { ..._9,
    ..._10,
    ..._11
  };
  export const OmniflixMinter = { ..._12,
    ..._13,
    ..._14
  };
  export const OmniflixOpenEditionMinter = { ..._15,
    ..._16,
    ..._17
  };
  export const OmniflixMultiMintOpenEditionMinter = { ..._18,
    ..._19,
    ..._20
  };
}