/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Timestamp, Uint64, Uint128, InstantiateMsg, CollectionDetails, WeightedAddress, OpenEditionMinterInitExtention, Coin, ExecuteMsg, QueryMsg, Addr, Decimal, Config, Uint32, Boolean, UserDetails, Token, ArrayOfAddr } from "./OmniflixMultiMintOpenEditionMinter.types";
export interface OmniflixMultiMintOpenEditionMinterReadOnlyInterface {
  contractAddress: string;
  collection: ({
    dropId
  }: {
    dropId?: number;
  }) => Promise<CollectionDetails>;
  config: ({
    dropId
  }: {
    dropId?: number;
  }) => Promise<Config>;
  mintedTokens: ({
    address,
    dropId
  }: {
    address: string;
    dropId?: number;
  }) => Promise<UserDetails>;
  totalMintedCount: ({
    dropId
  }: {
    dropId?: number;
  }) => Promise<Uint32>;
  tokensRemaining: ({
    dropId
  }: {
    dropId?: number;
  }) => Promise<Uint32>;
  isPaused: () => Promise<Boolean>;
  pausers: () => Promise<ArrayOfAddr>;
  currentDropNumber: () => Promise<Uint32>;
}
export class OmniflixMultiMintOpenEditionMinterQueryClient implements OmniflixMultiMintOpenEditionMinterReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.collection = this.collection.bind(this);
    this.config = this.config.bind(this);
    this.mintedTokens = this.mintedTokens.bind(this);
    this.totalMintedCount = this.totalMintedCount.bind(this);
    this.tokensRemaining = this.tokensRemaining.bind(this);
    this.isPaused = this.isPaused.bind(this);
    this.pausers = this.pausers.bind(this);
    this.currentDropNumber = this.currentDropNumber.bind(this);
  }

  collection = async ({
    dropId
  }: {
    dropId?: number;
  }): Promise<CollectionDetails> => {
    return this.client.queryContractSmart(this.contractAddress, {
      collection: {
        drop_id: dropId
      }
    });
  };
  config = async ({
    dropId
  }: {
    dropId?: number;
  }): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {
        drop_id: dropId
      }
    });
  };
  mintedTokens = async ({
    address,
    dropId
  }: {
    address: string;
    dropId?: number;
  }): Promise<UserDetails> => {
    return this.client.queryContractSmart(this.contractAddress, {
      minted_tokens: {
        address,
        drop_id: dropId
      }
    });
  };
  totalMintedCount = async ({
    dropId
  }: {
    dropId?: number;
  }): Promise<Uint32> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_minted_count: {
        drop_id: dropId
      }
    });
  };
  tokensRemaining = async ({
    dropId
  }: {
    dropId?: number;
  }): Promise<Uint32> => {
    return this.client.queryContractSmart(this.contractAddress, {
      tokens_remaining: {
        drop_id: dropId
      }
    });
  };
  isPaused = async (): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_paused: {}
    });
  };
  pausers = async (): Promise<ArrayOfAddr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pausers: {}
    });
  };
  currentDropNumber = async (): Promise<Uint32> => {
    return this.client.queryContractSmart(this.contractAddress, {
      current_drop_number: {}
    });
  };
}
export interface OmniflixMultiMintOpenEditionMinterInterface extends OmniflixMultiMintOpenEditionMinterReadOnlyInterface {
  contractAddress: string;
  sender: string;
  mint: ({
    dropId
  }: {
    dropId?: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  mintAdmin: ({
    dropId,
    recipient
  }: {
    dropId?: number;
    recipient: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateRoyaltyRatio: ({
    dropId,
    ratio
  }: {
    dropId?: number;
    ratio: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateMintPrice: ({
    dropId,
    mintPrice
  }: {
    dropId?: number;
    mintPrice: Coin;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateWhitelistAddress: ({
    address,
    dropId
  }: {
    address: string;
    dropId?: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setPausers: ({
    pausers
  }: {
    pausers: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  newDrop: ({
    baseUri,
    data,
    description,
    endTime,
    extensible,
    mintPrice,
    nsfw,
    perAddressLimit,
    previewUri,
    royaltyRatio,
    startTime,
    tokenLimit,
    tokenName,
    transferable,
    uriHash,
    whitelistAddress
  }: {
    baseUri?: string;
    data?: string;
    description?: string;
    endTime?: Timestamp;
    extensible?: boolean;
    mintPrice: Coin;
    nsfw?: boolean;
    perAddressLimit: number;
    previewUri?: string;
    royaltyRatio?: string;
    startTime: Timestamp;
    tokenLimit?: number;
    tokenName: string;
    transferable?: boolean;
    uriHash?: string;
    whitelistAddress?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateRoyaltyReceivers: ({
    receivers
  }: {
    receivers: WeightedAddress[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateDenom: ({
    description,
    name,
    previewUri
  }: {
    description?: string;
    name?: string;
    previewUri?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  purgeDenom: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OmniflixMultiMintOpenEditionMinterClient extends OmniflixMultiMintOpenEditionMinterQueryClient implements OmniflixMultiMintOpenEditionMinterInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
    this.mintAdmin = this.mintAdmin.bind(this);
    this.updateRoyaltyRatio = this.updateRoyaltyRatio.bind(this);
    this.updateMintPrice = this.updateMintPrice.bind(this);
    this.updateWhitelistAddress = this.updateWhitelistAddress.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.setPausers = this.setPausers.bind(this);
    this.newDrop = this.newDrop.bind(this);
    this.updateRoyaltyReceivers = this.updateRoyaltyReceivers.bind(this);
    this.updateDenom = this.updateDenom.bind(this);
    this.purgeDenom = this.purgeDenom.bind(this);
  }

  mint = async ({
    dropId
  }: {
    dropId?: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      mint: {
        drop_id: dropId
      }
    }, fee, memo, _funds);
  };
  mintAdmin = async ({
    dropId,
    recipient
  }: {
    dropId?: number;
    recipient: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      mint_admin: {
        drop_id: dropId,
        recipient
      }
    }, fee, memo, _funds);
  };
  updateRoyaltyRatio = async ({
    dropId,
    ratio
  }: {
    dropId?: number;
    ratio: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_royalty_ratio: {
        drop_id: dropId,
        ratio
      }
    }, fee, memo, _funds);
  };
  updateMintPrice = async ({
    dropId,
    mintPrice
  }: {
    dropId?: number;
    mintPrice: Coin;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_mint_price: {
        drop_id: dropId,
        mint_price: mintPrice
      }
    }, fee, memo, _funds);
  };
  updateWhitelistAddress = async ({
    address,
    dropId
  }: {
    address: string;
    dropId?: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_whitelist_address: {
        address,
        drop_id: dropId
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  setPausers = async ({
    pausers
  }: {
    pausers: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_pausers: {
        pausers
      }
    }, fee, memo, _funds);
  };
  newDrop = async ({
    baseUri,
    data,
    description,
    endTime,
    extensible,
    mintPrice,
    nsfw,
    perAddressLimit,
    previewUri,
    royaltyRatio,
    startTime,
    tokenLimit,
    tokenName,
    transferable,
    uriHash,
    whitelistAddress
  }: {
    baseUri?: string;
    data?: string;
    description?: string;
    endTime?: Timestamp;
    extensible?: boolean;
    mintPrice: Coin;
    nsfw?: boolean;
    perAddressLimit: number;
    previewUri?: string;
    royaltyRatio?: string;
    startTime: Timestamp;
    tokenLimit?: number;
    tokenName: string;
    transferable?: boolean;
    uriHash?: string;
    whitelistAddress?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      new_drop: {
        base_uri: baseUri,
        data,
        description,
        end_time: endTime,
        extensible,
        mint_price: mintPrice,
        nsfw,
        per_address_limit: perAddressLimit,
        preview_uri: previewUri,
        royalty_ratio: royaltyRatio,
        start_time: startTime,
        token_limit: tokenLimit,
        token_name: tokenName,
        transferable,
        uri_hash: uriHash,
        whitelist_address: whitelistAddress
      }
    }, fee, memo, _funds);
  };
  updateRoyaltyReceivers = async ({
    receivers
  }: {
    receivers: WeightedAddress[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_royalty_receivers: {
        receivers
      }
    }, fee, memo, _funds);
  };
  updateDenom = async ({
    description,
    name,
    previewUri
  }: {
    description?: string;
    name?: string;
    previewUri?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_denom: {
        description,
        name,
        preview_uri: previewUri
      }
    }, fee, memo, _funds);
  };
  purgeDenom = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      purge_denom: {}
    }, fee, memo, _funds);
  };
}