/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Addr, Uint128, InstantiateMsg, OpenEditionMinterFactoryParams, MultiMinterParams, Coin, ExecuteMsg, Timestamp, Uint64, Decimal, MinterInstantiateMsgForOpenEditionMinterInitExtention, AuthDetails, CollectionDetails, WeightedAddress, OpenEditionMinterInitExtention, TokenDetails, MinterInstantiateMsgForEmpty, Empty, QueryMsg, Boolean, ArrayOfCoin, ParamsResponse, ArrayOfAddr } from "./OmniflixOpenEditionMinterFactory.types";
export interface OmniflixOpenEditionMinterFactoryReadOnlyInterface {
  contractAddress: string;
  params: () => Promise<ParamsResponse>;
  isPaused: () => Promise<Boolean>;
  pausers: () => Promise<ArrayOfAddr>;
  openEditionMinterCreationFee: () => Promise<ArrayOfCoin>;
  multiMinterCreationFee: () => Promise<ArrayOfCoin>;
}
export class OmniflixOpenEditionMinterFactoryQueryClient implements OmniflixOpenEditionMinterFactoryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.params = this.params.bind(this);
    this.isPaused = this.isPaused.bind(this);
    this.pausers = this.pausers.bind(this);
    this.openEditionMinterCreationFee = this.openEditionMinterCreationFee.bind(this);
    this.multiMinterCreationFee = this.multiMinterCreationFee.bind(this);
  }

  params = async (): Promise<ParamsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      params: {}
    });
  };
  isPaused = async (): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_paused: {}
    });
  };
  pausers = async (): Promise<ArrayOfAddr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pausers: {}
    });
  };
  openEditionMinterCreationFee = async (): Promise<ArrayOfCoin> => {
    return this.client.queryContractSmart(this.contractAddress, {
      open_edition_minter_creation_fee: {}
    });
  };
  multiMinterCreationFee = async (): Promise<ArrayOfCoin> => {
    return this.client.queryContractSmart(this.contractAddress, {
      multi_minter_creation_fee: {}
    });
  };
}
export interface OmniflixOpenEditionMinterFactoryInterface extends OmniflixOpenEditionMinterFactoryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createOpenEditionMinter: ({
    msg
  }: {
    msg: MinterInstantiateMsgForOpenEditionMinterInitExtention;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  createMultiMintOpenEditionMinter: ({
    msg
  }: {
    msg: MinterInstantiateMsgForEmpty;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAdmin: ({
    admin
  }: {
    admin: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateFeeCollectorAddress: ({
    feeCollectorAddress
  }: {
    feeCollectorAddress: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateOpenEditionMinterCreationFee: ({
    openEditionMinterCreationFee
  }: {
    openEditionMinterCreationFee: Coin;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateOpenEditionMinterCodeId: ({
    openEditionMinterCodeId
  }: {
    openEditionMinterCodeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateMultiMinterCreationFee: ({
    multiMinterCreationFee
  }: {
    multiMinterCreationFee: Coin;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateMultiMinterCodeId: ({
    multiMinterCodeId
  }: {
    multiMinterCodeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setPausers: ({
    pausers
  }: {
    pausers: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OmniflixOpenEditionMinterFactoryClient extends OmniflixOpenEditionMinterFactoryQueryClient implements OmniflixOpenEditionMinterFactoryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createOpenEditionMinter = this.createOpenEditionMinter.bind(this);
    this.createMultiMintOpenEditionMinter = this.createMultiMintOpenEditionMinter.bind(this);
    this.updateAdmin = this.updateAdmin.bind(this);
    this.updateFeeCollectorAddress = this.updateFeeCollectorAddress.bind(this);
    this.updateOpenEditionMinterCreationFee = this.updateOpenEditionMinterCreationFee.bind(this);
    this.updateOpenEditionMinterCodeId = this.updateOpenEditionMinterCodeId.bind(this);
    this.updateMultiMinterCreationFee = this.updateMultiMinterCreationFee.bind(this);
    this.updateMultiMinterCodeId = this.updateMultiMinterCodeId.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.setPausers = this.setPausers.bind(this);
  }

  createOpenEditionMinter = async ({
    msg
  }: {
    msg: MinterInstantiateMsgForOpenEditionMinterInitExtention;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_open_edition_minter: {
        msg
      }
    }, fee, memo, _funds);
  };
  createMultiMintOpenEditionMinter = async ({
    msg
  }: {
    msg: MinterInstantiateMsgForEmpty;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_multi_mint_open_edition_minter: {
        msg
      }
    }, fee, memo, _funds);
  };
  updateAdmin = async ({
    admin
  }: {
    admin: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_admin: {
        admin
      }
    }, fee, memo, _funds);
  };
  updateFeeCollectorAddress = async ({
    feeCollectorAddress
  }: {
    feeCollectorAddress: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_fee_collector_address: {
        fee_collector_address: feeCollectorAddress
      }
    }, fee, memo, _funds);
  };
  updateOpenEditionMinterCreationFee = async ({
    openEditionMinterCreationFee
  }: {
    openEditionMinterCreationFee: Coin;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_open_edition_minter_creation_fee: {
        open_edition_minter_creation_fee: openEditionMinterCreationFee
      }
    }, fee, memo, _funds);
  };
  updateOpenEditionMinterCodeId = async ({
    openEditionMinterCodeId
  }: {
    openEditionMinterCodeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_open_edition_minter_code_id: {
        open_edition_minter_code_id: openEditionMinterCodeId
      }
    }, fee, memo, _funds);
  };
  updateMultiMinterCreationFee = async ({
    multiMinterCreationFee
  }: {
    multiMinterCreationFee: Coin;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_multi_minter_creation_fee: {
        multi_minter_creation_fee: multiMinterCreationFee
      }
    }, fee, memo, _funds);
  };
  updateMultiMinterCodeId = async ({
    multiMinterCodeId
  }: {
    multiMinterCodeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_multi_minter_code_id: {
        multi_minter_code_id: multiMinterCodeId
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  setPausers = async ({
    pausers
  }: {
    pausers: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_pausers: {
        pausers
      }
    }, fee, memo, _funds);
  };
}