/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  fee_collector_address: string;
  minter_creation_fee: Coin;
  open_edition_minter_code_id: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  create_minter: {
    msg: MinterInstantiateMsgForOpenEditionMinterInitExtention;
  };
} | {
  update_admin: {
    admin: string;
  };
} | {
  update_fee_collector_address: {
    fee_collector_address: string;
  };
} | {
  update_minter_creation_fee: {
    minter_creation_fee: Coin;
  };
} | {
  update_minter_code_id: {
    minter_code_id: number;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface MinterInstantiateMsgForOpenEditionMinterInitExtention {
  collection_details: CollectionDetails;
  init: OpenEditionMinterInitExtention;
}
export interface CollectionDetails {
  base_uri: string;
  data: string;
  description: string;
  extensible: boolean;
  id: string;
  name: string;
  nsfw: boolean;
  preview_uri: string;
  royalty_receivers?: WeightedAddress[] | null;
  schema: string;
  symbol: string;
  token_name: string;
  transferable: boolean;
  uri: string;
  uri_hash: string;
}
export interface WeightedAddress {
  address: string;
  weight: string;
  [k: string]: unknown;
}
export interface OpenEditionMinterInitExtention {
  admin: string;
  end_time?: Timestamp | null;
  mint_price: Coin;
  payment_collector?: string | null;
  per_address_limit: number;
  royalty_ratio: string;
  start_time: Timestamp;
  token_limit?: number | null;
  whitelist_address?: string | null;
}
export type QueryMsg = {
  params: {};
};
export type Addr = string;
export interface ParamsResponse {
  params: Params;
}
export interface Params {
  admin: Addr;
  fee_collector_address: Addr;
  minter_creation_fee: Coin;
  open_edition_minter_code_id: number;
}