/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Addr, Timestamp, Uint64, Uint128, Decimal, InstantiateMsg, AuthDetails, CollectionDetails, WeightedAddress, OpenEditionMinterInitExtention, Coin, TokenDetails, ExecuteMsg, Config, QueryMsg, QueryMsgExtension, Uint32, Boolean, MintHistoryResponse, ArrayOfAddr, UserDetails, Token } from "./OmniflixMultiMintOpenEditionMinter.types";
export interface OmniflixMultiMintOpenEditionMinterMsg {
  contractAddress: string;
  sender: string;
  mint: ({
    dropId
  }: {
    dropId?: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  mintAdmin: ({
    dropId,
    recipient
  }: {
    dropId?: number;
    recipient: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateRoyaltyRatio: ({
    dropId,
    ratio
  }: {
    dropId?: number;
    ratio: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateMintPrice: ({
    dropId,
    mintPrice
  }: {
    dropId?: number;
    mintPrice: Coin;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateWhitelistAddress: ({
    address,
    dropId
  }: {
    address: string;
    dropId?: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setPausers: ({
    pausers
  }: {
    pausers: string[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  newDrop: ({
    config,
    tokenDetails
  }: {
    config: Config;
    tokenDetails: TokenDetails;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeDrop: ({
    dropId
  }: {
    dropId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateRoyaltyReceivers: ({
    receivers
  }: {
    receivers: WeightedAddress[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateDenom: ({
    description,
    name,
    previewUri
  }: {
    description?: string;
    name?: string;
    previewUri?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  purgeDenom: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateAdmin: ({
    admin
  }: {
    admin: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updatePaymentCollector: ({
    paymentCollector
  }: {
    paymentCollector: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class OmniflixMultiMintOpenEditionMinterMsgComposer implements OmniflixMultiMintOpenEditionMinterMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
    this.mintAdmin = this.mintAdmin.bind(this);
    this.updateRoyaltyRatio = this.updateRoyaltyRatio.bind(this);
    this.updateMintPrice = this.updateMintPrice.bind(this);
    this.updateWhitelistAddress = this.updateWhitelistAddress.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.setPausers = this.setPausers.bind(this);
    this.newDrop = this.newDrop.bind(this);
    this.removeDrop = this.removeDrop.bind(this);
    this.updateRoyaltyReceivers = this.updateRoyaltyReceivers.bind(this);
    this.updateDenom = this.updateDenom.bind(this);
    this.purgeDenom = this.purgeDenom.bind(this);
    this.updateAdmin = this.updateAdmin.bind(this);
    this.updatePaymentCollector = this.updatePaymentCollector.bind(this);
  }

  mint = ({
    dropId
  }: {
    dropId?: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          mint: {
            drop_id: dropId
          }
        })),
        funds: _funds
      })
    };
  };
  mintAdmin = ({
    dropId,
    recipient
  }: {
    dropId?: number;
    recipient: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          mint_admin: {
            drop_id: dropId,
            recipient
          }
        })),
        funds: _funds
      })
    };
  };
  updateRoyaltyRatio = ({
    dropId,
    ratio
  }: {
    dropId?: number;
    ratio: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_royalty_ratio: {
            drop_id: dropId,
            ratio
          }
        })),
        funds: _funds
      })
    };
  };
  updateMintPrice = ({
    dropId,
    mintPrice
  }: {
    dropId?: number;
    mintPrice: Coin;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_mint_price: {
            drop_id: dropId,
            mint_price: mintPrice
          }
        })),
        funds: _funds
      })
    };
  };
  updateWhitelistAddress = ({
    address,
    dropId
  }: {
    address: string;
    dropId?: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_whitelist_address: {
            address,
            drop_id: dropId
          }
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  setPausers = ({
    pausers
  }: {
    pausers: string[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_pausers: {
            pausers
          }
        })),
        funds: _funds
      })
    };
  };
  newDrop = ({
    config,
    tokenDetails
  }: {
    config: Config;
    tokenDetails: TokenDetails;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          new_drop: {
            config,
            token_details: tokenDetails
          }
        })),
        funds: _funds
      })
    };
  };
  removeDrop = ({
    dropId
  }: {
    dropId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_drop: {
            drop_id: dropId
          }
        })),
        funds: _funds
      })
    };
  };
  updateRoyaltyReceivers = ({
    receivers
  }: {
    receivers: WeightedAddress[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_royalty_receivers: {
            receivers
          }
        })),
        funds: _funds
      })
    };
  };
  updateDenom = ({
    description,
    name,
    previewUri
  }: {
    description?: string;
    name?: string;
    previewUri?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_denom: {
            description,
            name,
            preview_uri: previewUri
          }
        })),
        funds: _funds
      })
    };
  };
  purgeDenom = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          purge_denom: {}
        })),
        funds: _funds
      })
    };
  };
  updateAdmin = ({
    admin
  }: {
    admin: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_admin: {
            admin
          }
        })),
        funds: _funds
      })
    };
  };
  updatePaymentCollector = ({
    paymentCollector
  }: {
    paymentCollector: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_payment_collector: {
            payment_collector: paymentCollector
          }
        })),
        funds: _funds
      })
    };
  };
}