/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  params: MinterFactoryParams;
}
export interface MinterFactoryParams {
  admin: Addr;
  fee_collector_address: Addr;
  minter_code_id: number;
  minter_creation_fee: Coin;
  product_label: string;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  create_minter: {
    msg: MinterInstantiateMsgForMinterInitExtention;
  };
} | {
  create_minter_with_migration: {
    msg: CreateMinterMsgWithMigration;
  };
} | {
  update_admin: {
    admin: string;
  };
} | {
  update_fee_collector_address: {
    fee_collector_address: string;
  };
} | {
  update_minter_creation_fee: {
    minter_creation_fee: Coin;
  };
} | {
  update_minter_code_id: {
    minter_code_id: number;
  };
} | {
  pause: {};
} | {
  unpause: {};
} | {
  set_pausers: {
    pausers: string[];
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Decimal = string;
export interface MinterInstantiateMsgForMinterInitExtention {
  auth_details: AuthDetails;
  collection_details: CollectionDetails;
  init?: MinterInitExtention | null;
  token_details?: TokenDetails | null;
}
export interface AuthDetails {
  admin: Addr;
  payment_collector: Addr;
}
export interface CollectionDetails {
  collection_name: string;
  data?: string | null;
  description?: string | null;
  id: string;
  preview_uri?: string | null;
  royalty_receivers?: WeightedAddress[] | null;
  schema?: string | null;
  symbol: string;
  uri?: string | null;
  uri_hash?: string | null;
}
export interface WeightedAddress {
  address: string;
  weight: string;
  [k: string]: unknown;
}
export interface MinterInitExtention {
  end_time?: Timestamp | null;
  mint_price: Coin;
  num_tokens: number;
  per_address_limit?: number | null;
  start_time: Timestamp;
  whitelist_address?: string | null;
}
export interface TokenDetails {
  base_token_uri: string;
  data?: string | null;
  description?: string | null;
  extensible: boolean;
  nsfw: boolean;
  preview_uri?: string | null;
  royalty_ratio: Decimal;
  token_name: string;
  transferable: boolean;
}
export interface CreateMinterMsgWithMigration {
  auth_details: AuthDetails;
  collection_details: CollectionDetails;
  config: Config;
  migration_data: MigrationData;
  token_details: TokenDetails;
}
export interface Config {
  end_time?: Timestamp | null;
  mint_price: Coin;
  num_tokens?: number | null;
  per_address_limit?: number | null;
  start_time: Timestamp;
  whitelist_address?: Addr | null;
}
export interface MigrationData {
  mintable_tokens: Token[];
  minted_count: number;
}
export interface Token {
  token_id: string;
}
export type QueryMsg = {
  params: {};
} | {
  is_paused: {};
} | {
  pausers: {};
} | {
  minter_creation_fee: {};
};
export type Boolean = boolean;
export type ArrayOfCoin = Coin[];
export interface ParamsResponse {
  params: MinterFactoryParams;
}
export type ArrayOfAddr = Addr[];