/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  params: FactoryParamsForMultiMinterFactoryExtension;
}
export interface FactoryParamsForMultiMinterFactoryExtension {
  admin: Addr;
  contract_id: number;
  creation_fee: Coin;
  fee_collector_address: Addr;
  init: MultiMinterFactoryExtension;
  product_label: string;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface MultiMinterFactoryExtension {
  multi_minter_contract_id: number;
  multi_minter_creation_fee: Coin;
}
export type ExecuteMsg = {
  create_open_edition_minter: {
    msg: MinterInstantiateMsgForOpenEditionMinterInitExtention;
  };
} | {
  create_multi_mint_open_edition_minter: {
    msg: MinterInstantiateMsgForMultiMinterInitExtention;
  };
} | {
  update_admin: {
    admin: string;
  };
} | {
  update_fee_collector_address: {
    fee_collector_address: string;
  };
} | {
  update_minter_creation_fee: {
    minter_creation_fee: Coin;
  };
} | {
  update_minter_code_id: {
    minter_code_id: number;
  };
} | {
  update_multi_minter_creation_fee: {
    multi_minter_creation_fee: Coin;
  };
} | {
  update_multi_minter_contract_id: {
    multi_minter_contract_id: number;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Decimal = string;
export interface MinterInstantiateMsgForOpenEditionMinterInitExtention {
  collection_details: CollectionDetails;
  init: OpenEditionMinterInitExtention;
  token_details?: TokenDetails | null;
}
export interface CollectionDetails {
  collection_name: string;
  data?: string | null;
  description?: string | null;
  id: string;
  preview_uri?: string | null;
  royalty_receivers?: WeightedAddress[] | null;
  schema?: string | null;
  symbol: string;
  uri?: string | null;
  uri_hash?: string | null;
}
export interface WeightedAddress {
  address: string;
  weight: string;
  [k: string]: unknown;
}
export interface OpenEditionMinterInitExtention {
  admin: string;
  end_time?: Timestamp | null;
  mint_price: Coin;
  num_tokens?: number | null;
  payment_collector?: string | null;
  per_address_limit?: number | null;
  start_time: Timestamp;
  whitelist_address?: string | null;
}
export interface TokenDetails {
  base_token_uri: string;
  data?: string | null;
  description?: string | null;
  extensible: boolean;
  nsfw: boolean;
  preview_uri?: string | null;
  royalty_ratio: Decimal;
  token_name: string;
  transferable: boolean;
}
export interface MinterInstantiateMsgForMultiMinterInitExtention {
  collection_details: CollectionDetails;
  init: MultiMinterInitExtention;
  token_details?: TokenDetails | null;
}
export interface MultiMinterInitExtention {
  admin: string;
  payment_collector?: string | null;
}
export type QueryMsg = {
  params: {};
};
export interface ParamsResponse {
  params: FactoryParamsForMultiMinterFactoryExtension;
}