/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export interface InstantiateMsg {
  admin: string;
  rounds: RoundConfig[];
}
export interface RoundConfig {
  members: string[];
  round: Round;
}
export interface Round {
  end_time: Timestamp;
  mint_price: Coin;
  round_per_address_limit: number;
  start_time: Timestamp;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  remove_round: {
    round_index: number;
  };
} | {
  add_round: {
    round_config: RoundConfig;
  };
} | {
  private_mint: {
    collector: string;
  };
} | {
  add_members: {
    members: string[];
    round_index: number;
  };
} | {
  update_price: {
    mint_price: Coin;
    round_index: number;
  };
};
export type QueryMsg = {
  rounds: {};
} | {
  round: {
    round_index: number;
  };
} | {
  is_active: {};
} | {
  active_round: {};
} | {
  members: {
    limit?: number | null;
    round_index: number;
    start_after?: string | null;
  };
} | {
  price: {};
} | {
  is_member: {
    address: string;
  };
} | {
  admin: {};
};
export type TupleOfUint8AndRound = [number, Round];
export type String = string;
export type Boolean = boolean;
export type ArrayOfString = string[];
export type ArrayOfTupleOfUint8AndRound = [number, Round][];