/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Round = {
  whitelist_address: {
    address: Addr;
    end_time?: Timestamp | null;
    mint_price: Uint128;
    round_limit: number;
    start_time?: Timestamp | null;
  };
} | {
  whitelist_collection: {
    collection_id: string;
    end_time: Timestamp;
    mint_price: Uint128;
    round_limit: number;
    start_time: Timestamp;
  };
};
export type Addr = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
  collection_details: CollectionDetails;
  creator?: string | null;
  mint_denom: string;
  mint_price: Uint128;
  payment_collector?: string | null;
  per_address_limit: number;
  rounds?: Round[] | null;
  royalty_ratio: string;
  start_time: Timestamp;
}
export interface CollectionDetails {
  base_uri: string;
  description: string;
  extensible: boolean;
  id: string;
  name: string;
  nsfw: boolean;
  num_tokens: number;
  preview_uri: string;
  schema: string;
  symbol: string;
}
export type ExecuteMsg = {
  mint: {};
} | {
  mint_admin: {
    denom_id?: string | null;
    recipient: string;
  };
} | {
  remove_round: {
    round_index: number;
  };
} | {
  add_round: {
    round: Round;
  };
} | {
  update_collection_round: {
    round: Round;
    round_index: number;
  };
} | {
  update_whitelist_round: {
    end_time?: Timestamp | null;
    mint_price?: Uint128 | null;
    round_limit?: number | null;
    start_time?: Timestamp | null;
  };
} | {
  burn_remaining_tokens: {};
} | {
  update_royalty_ratio: {
    ratio: string;
  };
} | {
  update_mint_price: {
    mint_price: Uint128;
  };
} | {
  randomize_list: {};
};
export type QueryMsg = {
  collection: {};
} | {
  config: {};
} | {
  mintable_tokens: {};
} | {
  minted_tokens: {
    address: string;
  };
} | {
  total_tokens: {};
} | {
  rounds: {};
};
export type Decimal = string;
export interface Config {
  creator: Addr;
  mint_denom: string;
  mint_price: Uint128;
  payment_collector: Addr;
  per_address_limit: number;
  royalty_ratio: Decimal;
  start_time: Timestamp;
}
export type ArrayOfToken = Token[];
export interface Token {
  token_id: string;
}
export interface UserDetails {
  minted_tokens: Token[];
  rounds_mints: MintCountInRound[];
  total_minted_count: number;
}
export interface MintCountInRound {
  count: number;
  round_index: number;
}
export type ArrayOfTupleOfUint32AndRound = [number, Round][];
export type Uint32 = number;